services:
  app:
    build:
      context: ../..
      dockerfile: Dockerfile
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/health"]
      interval: 30s
      timeout: 30s
      retries: 3

  app-air:
    image: golang:1.24-alpine
    working_dir: /app
    command: sh -c "go install github.com/air-verse/air@latest && air"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/health"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - ../..:/app
